### ISSUE TITLE
No way to specify parameters in @EnableExtendedRepositories annotation

### ISSUE THREAD

**Issue by mmatosevic** [infobip/infobip-spring-data-jpa-querydsl#1]
Since `@EnableExtendedRepositories` now replaces `@EnableJpaRepositories`, there is no way to specify parameters originally found in EnableJpaRepositories annotation.

`@EnableExtendedRepositories` should contain parameters like:
- basePackages
- repositoryBaseClass
- transactionManagerRef
- entityManagerFactoryRef
- and others.

Or provide any other way of achieving the same goal :)

**Comment by lpandzic** [comment]
With 1.0.1 you can use can use `@EnableJpaRepositories(repositoryBaseClass = SimpleExtendedQueryDslJpaRepository.class, ... other options)`

**Comment by jcheros** [comment]
Hi @lpandzic 
With the **Spring data upgrade** it is no longer possible to use that class because it is not public.
What can be done?

**Comment by lpandzic** [comment]
With 2.0.0 you should be able to use @EnableExtendedRepositories like mentioned in README.md.

**Comment by lpandzic** [comment]
@jcheros , do you need parameters of EnableJpaRepositories?

**Comment by jcheros** [comment]
Yes. I need this
`@EnableJpaRepositories (basePackages = "com.socamapa.jpa", repositoryBaseClass = SimpleExtendedQueryDslJpaRepository.class)`

But now that class is no longer **public** and it is not possible to use it with @EnableJpaRepositories

**Comment by lpandzic** [comment]
Fixed (https://github.com/infobip/infobip-spring-data-jpa-querydsl/issues/4)
